### ISSUE TITLE
The image name title is "cut off"

### ISSUE THREAD

**Issue by engage-results** [cloudy9101/obsidian-image-inserter#11]
This image name from Unsplash seems to be treated as fixed width, and the name is cut off when the image is included as a link.

Unless this is an API limitation I'd like to see the full title.

To reproduce:

This image on unsplash is called "Hedgie King"

https://unsplash.com/photos/iJ9o00UeAWk

When inserted into a note it's "Hedgie Kin" (this happens on all images I believe).

`![hedgie kin|100%](https://images.unsplash.com/photo-1534278931827-8a259344abe7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjAwOTd8MHwxfHNlYXJjaHw0fHxjdXRlfGVufDB8MHx8fDE2NzUyMzk4MjA&ixlib=rb-4.0.3&q=80&w=1080)`

**Comment by cloudy9101** [comment]
Hi @engage-results 

You're right. This plugin gets the image name from the image description from Unsplash and cuts off the desc to 10 characters long since I'm afraid the desc is too long. But now I reckon that's fine and it would fit your use case so I removed the cut-off logic. Now it will leave the complete desc as the image name.
Please update the plugin to v0.3.1

**Comment by engage-results** [comment]
Thanks! I got the update and saw the fix before I waw the issue tracker.  I appreciate it.
