### ISSUE TITLE
Images are low resolution

### ISSUE THREAD

**Issue by Explosion-Scratch** [cloudy9101/obsidian-image-inserter#18]
This seems to be from using `item.urls.regular` in the JSON response from the proxy instead of `.raw` or `.full`

Fixed in PR #17

**Comment by cloudy9101** [comment]
Hi @Explosion-Scratch, 

Thanks for the PR. I appreciate your work.
I'm worried about the loading speed of the image if we use `.raw` or `.full`. We already have an option for image size, so I think we can use that to construct the image URL with the right size.

I intend to get the correct image width from the `image size` option and use it to build the image URL for loading/downloading the image. Then, I'll set the default `image size` to `1080`.

If you can do that, it would be great. Otherwise, I can do it next week.

**Comment by Explosion-Scratch** [comment]
@cloudy9101 I updated my PR! See 4c6828b1b6e83c632e30d60d3903fda9f697a483

**Comment by cloudy9101** [comment]
Hi @Explosion-Scratch 
After considering it, I've added the ability to select image quality when inserting an image. You can also set a default image quality, and choose `raw` to meet your requirements.
It's available in the 0.6.1 version.
